name = "countdown"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
AWS_REGION = "eu-west-3"
WEBSITE_NAME = "Tickr"
WEBSITE_URL = "http://localhost:5173"

[env.production.vars]
AWS_REGION = "eu-west-3"
SEND_INVITATION_FROM = "countdown@meow-meow.dev"
WEBSITE_NAME = "Tickr"
WEBSITE_URL = "countdown.meow-meow.dev"
