name = "countdown"
pages_build_output_dir = "."
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
WEBSITE_NAME = "Tickr"
AWS_REGION = "eu-west-3"

[env.production.vars]
WEBSITE_URL = "countdown.meow-meow.dev"
