on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10.2.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 21
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate code
        run: pnpm generate_code

      - name: Run TypeScript type checks
        run: pnpm tsc:check

      - name: Run unit tests
        run: pnpm unit_tests
        env:
          COUNTDOWN_DEVELOPMENT_AWS_SECRET_ACCESS_KEY: "xxx"

      - name: Run lint
        run: pnpm lint:check

      - name: Run prettier
        run: pnpm prettier:check
